[workspace]
resolver = "2"
members = [
	"crates/squawk-lexer",
	"crates/squawk-parser",
	"crates/squawk-semantic",
	"crates/squawk-codegen",
	"crates/squawk-vm",
	"crates/squawk-regex",
	"crates/squawk-runtime",
	"crates/squawk"
]


[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Chubak Bidpaa <chubakbidpaa@riseup.net>"]
license = "MIT"
repository = "https://github.com/Chubek/Squawk"

[workspace.dependencies]
thiserror = "1.0"
anyhow = "1.0"

squawk-lexer = { path = "crates/squawk-lexer" }
squawk-parser = { path = "crates/squawk-parser" }
squawk-semantic = { path = "crates/squawk-semantic" }
squawk-codgen = { path = "crates/squawk-codegen" }
squawk-vm = { path = "crates/squawk-vm" }
squawk-regex = { path = "crates/squawk-regex" }
squawk-runtime = { path = "crates/squawk-runtime" }

